### ISSUE TITLE
[BUG] Docker registry upgrade error 1.8.0 (docker install, after successful paperless-ng to -ngx migration 1.7.0)

### ISSUE THREAD

**Issue by pkoerner81929** [paperless-ngx/paperless-ngx#1351]
### Description

I have upgraded a previous docker -ng installation successfully to -ngx 1.6.0. and to 1.7.0 without problems. When upgrading to 1.8.0 only the webserver is updated (and works as V1.8.0), but I got errors regarding the non webserver images. I assume some legacy settings.

**Error at "docker-compose pull"**

```
$docker-compose pull
Pulling broker    ... error
Pulling db        ... error
Pulling gotenberg ... error
Pulling tika      ... error
Pulling webserver ... done

ERROR: for broker  Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable

ERROR: for tika  Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable

ERROR: for db  Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable

ERROR: for gotenberg  Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable
ERROR: Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable
Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable
Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable
Get "https://registry-1.docker.io/v2/": dial tcp 44.207.51.64:443: connect: network is unreachable
```

**Current docker-compse.yml file (extract):** 

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: xxxxxxxxxxxx

  webserver:
#    image: jonaswinkler/paperless-ng:latest
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000


```

### Steps to reproduce

Regular update process: stop paperless-ngx, run docker-compose pull.

### Paperless-ngx version

1.8.0

### Host OS

Raspberry Pi

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
It looks like Docker Hub had a brief outage issue today with their registry: https://status.docker.com/pages/history/533c6539221ae15e3f000031

Each container which failed is coming from the Docker Hub, but the issue says it is resolved so a normal pull should work again.

**Comment by pkoerner81929** [comment]
Thanks for the feedback, that was the last I expected ;-) 
Still does not work, but I will keep trying.

**Comment by stumpylog** [comment]
You could try a "docker pull alpine:latest" to check against another well used image.  I expect it would fail too.  I do think it's just a blip in the Docker Hub registry
