### ISSUE TITLE
[BUG] PDF Consumption Issue - Ghostscript rasterizing failed - (https://github.com/ocrmypdf/OCRmyPDF/issues/962)

### ISSUE THREAD

**Issue by upuldi** [paperless-ngx/paperless-ngx#875]
### Description
```
[2022-05-04 11:19:39,039] [ERROR] [paperless.consumer] Error while consuming document 220407-Concept_01(XXXXXXXXX) (4).pdf: SubprocessOutputError: Ghostscript rasterizing failed

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 126, in rasterize_pdf
    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=2', '-dLastPage=2', '-r10613.793103x10613.793103', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.5aaq4owc/origin.pdf']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 187, in exec_page_sync
    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 344, in rasterize_preview
    page_context.plugin_manager.hook.rasterize_pdf_page(
  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page
    ghostscript.rasterize_pdf(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 129, in rasterize_pdf
    raise SubprocessOutputError('Ghostscript rasterizing failed')
ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}")
documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed
```

### Steps to reproduce

1. Upload some PDFs to the consumption. 
2. PDF is not corrupted but Paperless can not consume it. 

### Paperless-ngx version

Latest

### Host OS

Unraid

### Installation method

Docker

**Comment by stumpylog** [comment]
As it looks like you've surmised from ocrmypdf/OCRmyPDF/issues/952, this isn't something we'll be able to fix.  If you can, providing a test file to the upstream project will help them investigate further.

**Comment by upuldi** [comment]
Hi All, Pls find the upstream project comments about this issue. Apparently, the ocrmypdf is passing different values to the ghostscript causing this issue. 

https://github.com/ocrmypdf/OCRmyPDF/issues/962

You can recreate this issue with the following PDF file. 
https://drive.google.com/file/d/16mHk7_HICNOpJk9JoHot5-NiEnLaGTKf/view?usp=sharing

**Comment by stumpylog** [comment]
File attached for reproducing.

[220426-Concept_04(North Kellyville_6 Flushing Meadow Rd) 2.pdf](https://github.com/paperless-ngx/paperless-ngx/files/8716684/220426-Concept_04.North.Kellyville_6.Flushing.Meadow.Rd.2.pdf)

**Comment by stumpylog** [comment]
Uploading that file to 1.7.1, it consumes without issue.  So this was likely solved by the minor ocrmypdf update.

**Comment by upuldi** [comment]
> ocrmypdf
I am still getting this issue on Paperless-ngx 1.7.1

**Comment by upuldi** [comment]
I just did a force update and checked the version of the ocrmypdf, it is 13.4.3 but still getting the same issue. I am running Paperless as a docker on Unraid. 

`    root@560060e10de3:/usr/src/paperless/src# ocrmypdf --version
13.4.3
`

**Same Error**

```
[2022-05-19 12:54:40,819] [ERROR] [paperless.consumer] Error while consuming document 220426-Concept_04(North Kellyville_6 Flushing Meadow Rd).pdf: SubprocessOutputError: Ghostscript rasterizing failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 126, in rasterize_pdf

    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run

    proc = subprocess_run(args, env=env, **kwargs)

  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=2', '-dLastPage=2', '-r4973.684211x4973.684211', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.royskqr0/origin.pdf']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline

    exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__

    self._execute(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute

    result = future.result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 187, in exec_page_sync

    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 344, in rasterize_preview

    page_context.plugin_manager.hook.rasterize_pdf_page(

  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__

    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall

    return outcome.get_result()

  File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result

    raise ex[1].with_traceback(ex[2])

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall

    res = hook_impl.function(*args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page

    ghostscript.rasterize_pdf(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 129, in rasterize_pdf

    raise SubprocessOutputError('Ghostscript rasterizing failed')

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse

    raise ParseError(f"{e.__class__.__name__}: {str(e)}")

documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed

```
I m using the following container 
```
https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx
```
dpkg log

```
root@560060e10de3:/var/log# cat dpkg.log 
2022-05-19 12:35:41 startup archives unpack
2022-05-19 12:35:42 install perl-modules-5.32:all <none> 5.32.1-4+deb11u2
2022-05-19 12:35:42 status half-installed perl-modules-5.32:all 5.32.1-4+deb11u2
2022-05-19 12:35:55 status unpacked perl-modules-5.32:all 5.32.1-4+deb11u2
2022-05-19 12:35:56 install libgdbm-compat4:amd64 <none> 1.19-2
2022-05-19 12:35:56 status triggers-pending libc-bin:amd64 2.31-13+deb11u3
2022-05-19 12:35:57 status half-installed libgdbm-compat4:amd64 1.19-2
2022-05-19 12:35:59 status unpacked libgdbm-compat4:amd64 1.19-2
2022-05-19 12:36:00 install libperl5.32:amd64 <none> 5.32.1-4+deb11u2
2022-05-19 12:36:00 status half-installed libperl5.32:amd64 5.32.1-4+deb11u2
2022-05-19 12:36:08 status unpacked libperl5.32:amd64 5.32.1-4+deb11u2
2022-05-19 12:36:12 install perl:amd64 <none> 5.32.1-4+deb11u2
2022-05-19 12:36:12 status half-installed perl:amd64 5.32.1-4+deb11u2
2022-05-19 12:36:14 status unpacked perl:amd64 5.32.1-4+deb11u2
2022-05-19 12:36:16 install bzip2:amd64 <none> 1.0.8-4
2022-05-19 12:36:16 status half-installed bzip2:amd64 1.0.8-4
2022-05-19 12:36:17 status unpacked bzip2:amd64 1.0.8-4
2022-05-19 12:36:18 install mailcap:all <none> 3.69
2022-05-19 12:36:18 status half-installed mailcap:all 3.69
2022-05-19 12:36:20 status unpacked mailcap:all 3.69
2022-05-19 12:36:21 install mime-support:all <none> 3.66
2022-05-19 12:36:21 status half-installed mime-support:all 3.66
2022-05-19 12:36:22 status unpacked mime-support:all 3.66
2022-05-19 12:36:23 install xz-utils:amd64 <none> 5.2.5-2.1~deb11u1
2022-05-19 12:36:23 status half-installed xz-utils:amd64 5.2.5-2.1~deb11u1
2022-05-19 12:36:25 status unpacked xz-utils:amd64 5.2.5-2.1~deb11u1
2022-05-19 12:36:26 install python3-chardet:all <none> 4.0.0-1
2022-05-19 12:36:26 status half-installed python3-chardet:all 4.0.0-1
2022-05-19 12:36:28 status unpacked python3-chardet:all 4.0.0-1
2022-05-19 12:36:29 install python3-cffi-backend:amd64 <none> 1.14.5-1
2022-05-19 12:36:29 status half-installed python3-cffi-backend:amd64 1.14.5-1
2022-05-19 12:36:30 status unpacked python3-cffi-backend:amd64 1.14.5-1
2022-05-19 12:36:31 install python3-six:all <none> 1.16.0-2
2022-05-19 12:36:31 status half-installed python3-six:all 1.16.0-2
2022-05-19 12:36:32 status unpacked python3-six:all 1.16.0-2
2022-05-19 12:36:33 install python3-cryptography:amd64 <none> 3.3.2-1
2022-05-19 12:36:33 status half-installed python3-cryptography:amd64 3.3.2-1
2022-05-19 12:36:36 status unpacked python3-cryptography:amd64 3.3.2-1
2022-05-19 12:36:37 install python3-sortedcontainers:all <none> 2.1.0-2
2022-05-19 12:36:37 status half-installed python3-sortedcontainers:all 2.1.0-2
2022-05-19 12:36:38 status unpacked python3-sortedcontainers:all 2.1.0-2
2022-05-19 12:36:39 install python3-pdfminer:all <none> 20200726-1
2022-05-19 12:36:39 status half-installed python3-pdfminer:all 20200726-1
2022-05-19 12:36:43 status unpacked python3-pdfminer:all 20200726-1
2022-05-19 12:36:45 install python3-pil:amd64 <none> 8.1.2+dfsg-0.3+deb11u1
2022-05-19 12:36:45 status half-installed python3-pil:amd64 8.1.2+dfsg-0.3+deb11u1
2022-05-19 12:36:47 status unpacked python3-pil:amd64 8.1.2+dfsg-0.3+deb11u1
2022-05-19 12:36:48 install python3-reportlab-accel:amd64 <none> 3.5.59-2
2022-05-19 12:36:48 status half-installed python3-reportlab-accel:amd64 3.5.59-2
2022-05-19 12:36:49 status unpacked python3-reportlab-accel:amd64 3.5.59-2
2022-05-19 12:36:50 install python3-reportlab:all <none> 3.5.59-2
2022-05-19 12:36:50 status half-installed python3-reportlab:all 3.5.59-2
2022-05-19 12:36:54 status unpacked python3-reportlab:all 3.5.59-2
2022-05-19 12:36:56 install python3-more-itertools:all <none> 4.2.0-3
2022-05-19 12:36:56 status half-installed python3-more-itertools:all 4.2.0-3
2022-05-19 12:36:57 status unpacked python3-more-itertools:all 4.2.0-3
2022-05-19 12:36:58 install python3-zipp:all <none> 1.0.0-3
2022-05-19 12:36:58 status half-installed python3-zipp:all 1.0.0-3
2022-05-19 12:37:00 status unpacked python3-zipp:all 1.0.0-3
2022-05-19 12:37:01 install python3-importlib-metadata:all <none> 1.6.0-2
2022-05-19 12:37:01 status half-installed python3-importlib-metadata:all 1.6.0-2
2022-05-19 12:37:02 status unpacked python3-importlib-metadata:all 1.6.0-2
2022-05-19 12:37:03 install python3-pluggy:all <none> 0.13.0-6
2022-05-19 12:37:03 status half-installed python3-pluggy:all 0.13.0-6
2022-05-19 12:37:04 status unpacked python3-pluggy:all 0.13.0-6
2022-05-19 12:37:05 install python3-humanfriendly:all <none> 9.1-1
2022-05-19 12:37:05 status half-installed python3-humanfriendly:all 9.1-1
2022-05-19 12:37:07 status unpacked python3-humanfriendly:all 9.1-1
2022-05-19 12:37:08 install python3-coloredlogs:all <none> 7.3-2
2022-05-19 12:37:08 status half-installed python3-coloredlogs:all 7.3-2
2022-05-19 12:37:09 status unpacked python3-coloredlogs:all 7.3-2
2022-05-19 12:37:12 install python3-lxml:amd64 <none> 4.6.3+dfsg-0.1+deb11u1
2022-05-19 12:37:12 status half-installed python3-lxml:amd64 4.6.3+dfsg-0.1+deb11u1
2022-05-19 12:37:15 status unpacked python3-lxml:amd64 4.6.3+dfsg-0.1+deb11u1
2022-05-19 12:37:16 install python3-pikepdf:amd64 <none> 1.17.3+dfsg-5
2022-05-19 12:37:16 status half-installed python3-pikepdf:amd64 1.17.3+dfsg-5
2022-05-19 12:37:18 status unpacked python3-pikepdf:amd64 1.17.3+dfsg-5
2022-05-19 12:37:19 install python3-img2pdf:all <none> 0.4.0-1
2022-05-19 12:37:19 status half-installed python3-img2pdf:all 0.4.0-1
2022-05-19 12:37:20 status unpacked python3-img2pdf:all 0.4.0-1
2022-05-19 12:37:22 install python3-tqdm:all <none> 4.57.0-2
2022-05-19 12:37:22 status half-installed python3-tqdm:all 4.57.0-2
2022-05-19 12:37:23 status unpacked python3-tqdm:all 4.57.0-2
2022-05-19 12:37:24 install ocrmypdf:all <none> 10.3.1+dfsg-1
2022-05-19 12:37:24 status half-installed ocrmypdf:all 10.3.1+dfsg-1
2022-05-19 12:37:26 status unpacked ocrmypdf:all 10.3.1+dfsg-1
2022-05-19 12:37:27 install python3-soupsieve:all <none> 2.2.1-1
2022-05-19 12:37:27 status half-installed python3-soupsieve:all 2.2.1-1
2022-05-19 12:37:28 status unpacked python3-soupsieve:all 2.2.1-1
2022-05-19 12:37:29 install python3-bs4:all <none> 4.9.3-1
2022-05-19 12:37:29 status half-installed python3-bs4:all 4.9.3-1
2022-05-19 12:37:31 status unpacked python3-bs4:all 4.9.3-1
2022-05-19 12:37:32 install python3-webencodings:all <none> 0.5.1-2
2022-05-19 12:37:32 status half-installed python3-webencodings:all 0.5.1-2
2022-05-19 12:37:33 status unpacked python3-webencodings:all 0.5.1-2
2022-05-19 12:37:34 install python3-html5lib:all <none> 1.1-3
2022-05-19 12:37:34 status half-installed python3-html5lib:all 1.1-3
2022-05-19 12:37:36 status unpacked python3-html5lib:all 1.1-3
2022-05-19 12:37:37 install python3-olefile:all <none> 0.46-3
2022-05-19 12:37:37 status half-installed python3-olefile:all 0.46-3
2022-05-19 12:37:39 status unpacked python3-olefile:all 0.46-3
2022-05-19 12:37:39 install python3-renderpm:amd64 <none> 3.5.59-2
2022-05-19 12:37:39 status half-installed python3-renderpm:amd64 3.5.59-2
2022-05-19 12:37:41 status unpacked python3-renderpm:amd64 3.5.59-2
2022-05-19 12:37:42 startup packages configure
2022-05-19 12:37:42 configure python3-renderpm:amd64 3.5.59-2 <none>
2022-05-19 12:37:42 status unpacked python3-renderpm:amd64 3.5.59-2
2022-05-19 12:37:43 status half-configured python3-renderpm:amd64 3.5.59-2
2022-05-19 12:37:43 status installed python3-renderpm:amd64 3.5.59-2
2022-05-19 12:37:44 configure python3-olefile:all 0.46-3 <none>
2022-05-19 12:37:44 status unpacked python3-olefile:all 0.46-3
2022-05-19 12:37:44 status half-configured python3-olefile:all 0.46-3
2022-05-19 12:37:45 status installed python3-olefile:all 0.46-3
2022-05-19 12:37:45 configure perl-modules-5.32:all 5.32.1-4+deb11u2 <none>
2022-05-19 12:37:45 status unpacked perl-modules-5.32:all 5.32.1-4+deb11u2
2022-05-19 12:37:45 status half-configured perl-modules-5.32:all 5.32.1-4+deb11u2
2022-05-19 12:37:46 status installed perl-modules-5.32:all 5.32.1-4+deb11u2
2022-05-19 12:37:46 configure python3-tqdm:all 4.57.0-2 <none>
2022-05-19 12:37:46 status unpacked python3-tqdm:all 4.57.0-2
2022-05-19 12:37:47 status half-configured python3-tqdm:all 4.57.0-2
2022-05-19 12:37:47 status installed python3-tqdm:all 4.57.0-2
2022-05-19 12:37:48 configure python3-sortedcontainers:all 2.1.0-2 <none>
2022-05-19 12:37:48 status unpacked python3-sortedcontainers:all 2.1.0-2
2022-05-19 12:37:48 status half-configured python3-sortedcontainers:all 2.1.0-2
2022-05-19 12:37:48 status installed python3-sortedcontainers:all 2.1.0-2
2022-05-19 12:37:49 configure bzip2:amd64 1.0.8-4 <none>
2022-05-19 12:37:49 status unpacked bzip2:amd64 1.0.8-4
2022-05-19 12:37:49 status half-configured bzip2:amd64 1.0.8-4
2022-05-19 12:37:49 status installed bzip2:amd64 1.0.8-4
2022-05-19 12:37:50 configure python3-webencodings:all 0.5.1-2 <none>
2022-05-19 12:37:50 status unpacked python3-webencodings:all 0.5.1-2
2022-05-19 12:37:50 status half-configured python3-webencodings:all 0.5.1-2
2022-05-19 12:37:51 status installed python3-webencodings:all 0.5.1-2
2022-05-19 12:37:51 configure python3-six:all 1.16.0-2 <none>
2022-05-19 12:37:51 status unpacked python3-six:all 1.16.0-2
2022-05-19 12:37:51 status half-configured python3-six:all 1.16.0-2
2022-05-19 12:37:52 status installed python3-six:all 1.16.0-2
2022-05-19 12:37:52 configure python3-chardet:all 4.0.0-1 <none>
2022-05-19 12:37:52 status unpacked python3-chardet:all 4.0.0-1
2022-05-19 12:37:53 status half-configured python3-chardet:all 4.0.0-1
2022-05-19 12:37:53 status installed python3-chardet:all 4.0.0-1
2022-05-19 12:37:54 configure python3-humanfriendly:all 9.1-1 <none>
2022-05-19 12:37:54 status unpacked python3-humanfriendly:all 9.1-1
2022-05-19 12:37:54 status half-configured python3-humanfriendly:all 9.1-1
2022-05-19 12:37:55 status installed python3-humanfriendly:all 9.1-1
2022-05-19 12:37:55 configure xz-utils:amd64 5.2.5-2.1~deb11u1 <none>
2022-05-19 12:37:55 status unpacked xz-utils:amd64 5.2.5-2.1~deb11u1
2022-05-19 12:37:55 status half-configured xz-utils:amd64 5.2.5-2.1~deb11u1
2022-05-19 12:37:56 status installed xz-utils:amd64 5.2.5-2.1~deb11u1
2022-05-19 12:37:56 configure python3-reportlab-accel:amd64 3.5.59-2 <none>
2022-05-19 12:37:56 status unpacked python3-reportlab-accel:amd64 3.5.59-2
2022-05-19 12:37:56 status half-configured python3-reportlab-accel:amd64 3.5.59-2
2022-05-19 12:37:57 status installed python3-reportlab-accel:amd64 3.5.59-2
2022-05-19 12:37:58 configure libgdbm-compat4:amd64 1.19-2 <none>
2022-05-19 12:37:58 status unpacked libgdbm-compat4:amd64 1.19-2
2022-05-19 12:37:58 status half-configured libgdbm-compat4:amd64 1.19-2
2022-05-19 12:37:58 status installed libgdbm-compat4:amd64 1.19-2
2022-05-19 12:37:58 configure python3-html5lib:all 1.1-3 <none>
2022-05-19 12:37:58 status unpacked python3-html5lib:all 1.1-3
2022-05-19 12:37:59 status half-configured python3-html5lib:all 1.1-3
2022-05-19 12:37:59 status installed python3-html5lib:all 1.1-3
2022-05-19 12:38:00 configure libperl5.32:amd64 5.32.1-4+deb11u2 <none>
2022-05-19 12:38:00 status unpacked libperl5.32:amd64 5.32.1-4+deb11u2
2022-05-19 12:38:01 status half-configured libperl5.32:amd64 5.32.1-4+deb11u2
2022-05-19 12:38:01 status installed libperl5.32:amd64 5.32.1-4+deb11u2
2022-05-19 12:38:01 configure python3-lxml:amd64 4.6.3+dfsg-0.1+deb11u1 <none>
2022-05-19 12:38:01 status unpacked python3-lxml:amd64 4.6.3+dfsg-0.1+deb11u1
2022-05-19 12:38:01 status half-configured python3-lxml:amd64 4.6.3+dfsg-0.1+deb11u1
2022-05-19 12:38:02 status installed python3-lxml:amd64 4.6.3+dfsg-0.1+deb11u1
2022-05-19 12:38:02 configure python3-coloredlogs:all 7.3-2 <none>
2022-05-19 12:38:02 status unpacked python3-coloredlogs:all 7.3-2
2022-05-19 12:38:03 status half-configured python3-coloredlogs:all 7.3-2
2022-05-19 12:38:03 status installed python3-coloredlogs:all 7.3-2
2022-05-19 12:38:03 configure python3-soupsieve:all 2.2.1-1 <none>
2022-05-19 12:38:03 status unpacked python3-soupsieve:all 2.2.1-1
2022-05-19 12:38:04 status half-configured python3-soupsieve:all 2.2.1-1
2022-05-19 12:38:04 status installed python3-soupsieve:all 2.2.1-1
2022-05-19 12:38:05 configure python3-cffi-backend:amd64 1.14.5-1 <none>
2022-05-19 12:38:05 status unpacked python3-cffi-backend:amd64 1.14.5-1
2022-05-19 12:38:05 status half-configured python3-cffi-backend:amd64 1.14.5-1
2022-05-19 12:38:06 status installed python3-cffi-backend:amd64 1.14.5-1
2022-05-19 12:38:06 configure python3-more-itertools:all 4.2.0-3 <none>
2022-05-19 12:38:06 status unpacked python3-more-itertools:all 4.2.0-3
2022-05-19 12:38:06 status half-configured python3-more-itertools:all 4.2.0-3
2022-05-19 12:38:07 status installed python3-more-itertools:all 4.2.0-3
2022-05-19 12:38:07 configure python3-zipp:all 1.0.0-3 <none>
2022-05-19 12:38:07 status unpacked python3-zipp:all 1.0.0-3
2022-05-19 12:38:08 status half-configured python3-zipp:all 1.0.0-3
2022-05-19 12:38:08 status installed python3-zipp:all 1.0.0-3
2022-05-19 12:38:09 configure python3-bs4:all 4.9.3-1 <none>
2022-05-19 12:38:09 status unpacked python3-bs4:all 4.9.3-1
2022-05-19 12:38:09 status half-configured python3-bs4:all 4.9.3-1
2022-05-19 12:38:09 status installed python3-bs4:all 4.9.3-1
2022-05-19 12:38:10 configure perl:amd64 5.32.1-4+deb11u2 <none>
2022-05-19 12:38:10 status unpacked perl:amd64 5.32.1-4+deb11u2
2022-05-19 12:38:11 status half-configured perl:amd64 5.32.1-4+deb11u2
2022-05-19 12:38:11 status installed perl:amd64 5.32.1-4+deb11u2
2022-05-19 12:38:12 configure python3-cryptography:amd64 3.3.2-1 <none>
2022-05-19 12:38:12 status unpacked python3-cryptography:amd64 3.3.2-1
2022-05-19 12:38:12 status half-configured python3-cryptography:amd64 3.3.2-1
2022-05-19 12:38:13 status installed python3-cryptography:amd64 3.3.2-1
2022-05-19 12:38:13 configure mailcap:all 3.69 <none>
2022-05-19 12:38:13 status unpacked mailcap:all 3.69
2022-05-19 12:38:14 status half-configured mailcap:all 3.69
2022-05-19 12:38:14 status installed mailcap:all 3.69
2022-05-19 12:38:15 configure python3-pdfminer:all 20200726-1 <none>
2022-05-19 12:38:15 status unpacked python3-pdfminer:all 20200726-1
2022-05-19 12:38:15 status half-configured python3-pdfminer:all 20200726-1
2022-05-19 12:38:16 status installed python3-pdfminer:all 20200726-1
2022-05-19 12:38:16 configure mime-support:all 3.66 <none>
2022-05-19 12:38:16 status unpacked mime-support:all 3.66
2022-05-19 12:38:17 status half-configured mime-support:all 3.66
2022-05-19 12:38:17 status installed mime-support:all 3.66
2022-05-19 12:38:17 configure python3-importlib-metadata:all 1.6.0-2 <none>
2022-05-19 12:38:17 status unpacked python3-importlib-metadata:all 1.6.0-2
2022-05-19 12:38:18 status half-configured python3-importlib-metadata:all 1.6.0-2
2022-05-19 12:38:19 status installed python3-importlib-metadata:all 1.6.0-2
2022-05-19 12:38:19 configure python3-pil:amd64 8.1.2+dfsg-0.3+deb11u1 <none>
2022-05-19 12:38:19 status unpacked python3-pil:amd64 8.1.2+dfsg-0.3+deb11u1
2022-05-19 12:38:19 status half-configured python3-pil:amd64 8.1.2+dfsg-0.3+deb11u1
2022-05-19 12:38:20 status installed python3-pil:amd64 8.1.2+dfsg-0.3+deb11u1
2022-05-19 12:38:20 configure python3-pluggy:all 0.13.0-6 <none>
2022-05-19 12:38:20 status unpacked python3-pluggy:all 0.13.0-6
2022-05-19 12:38:21 status half-configured python3-pluggy:all 0.13.0-6
2022-05-19 12:38:21 status installed python3-pluggy:all 0.13.0-6
2022-05-19 12:38:21 configure python3-reportlab:all 3.5.59-2 <none>
2022-05-19 12:38:21 status unpacked python3-reportlab:all 3.5.59-2
2022-05-19 12:38:22 status half-configured python3-reportlab:all 3.5.59-2
2022-05-19 12:38:23 status installed python3-reportlab:all 3.5.59-2
2022-05-19 12:38:24 configure python3-pikepdf:amd64 1.17.3+dfsg-5 <none>
2022-05-19 12:38:24 status unpacked python3-pikepdf:amd64 1.17.3+dfsg-5
2022-05-19 12:38:24 status half-configured python3-pikepdf:amd64 1.17.3+dfsg-5
2022-05-19 12:38:25 status installed python3-pikepdf:amd64 1.17.3+dfsg-5
2022-05-19 12:38:26 configure python3-img2pdf:all 0.4.0-1 <none>
2022-05-19 12:38:26 status unpacked python3-img2pdf:all 0.4.0-1
2022-05-19 12:38:26 status half-configured python3-img2pdf:all 0.4.0-1
2022-05-19 12:38:26 status installed python3-img2pdf:all 0.4.0-1
2022-05-19 12:38:27 configure ocrmypdf:all 10.3.1+dfsg-1 <none>
2022-05-19 12:38:27 status unpacked ocrmypdf:all 10.3.1+dfsg-1
2022-05-19 12:38:27 status half-configured ocrmypdf:all 10.3.1+dfsg-1
2022-05-19 12:38:28 status installed ocrmypdf:all 10.3.1+dfsg-1
2022-05-19 12:38:29 trigproc libc-bin:amd64 2.31-13+deb11u3 <none>
2022-05-19 12:38:29 status half-configured libc-bin:amd64 2.31-13+deb11u3
2022-05-19 12:38:31 status installed libc-bin:amd64 2.31-13+deb11u3

```

**Comment by stumpylog** [comment]
It must come down to a configuration option then.  What environment settings are you using?

I'm unsure what the dpkg.log is, could you explain it?

**Comment by upuldi** [comment]
dpkg.log is for showing all the packages installed and updated on the docker. 

Pls, find my configuration below.
https://drive.google.com/file/d/1TzOS8zyWhP8bOZz4-NSfJTbEe_oLBIyX/view?usp=sharing

**Comment by stumpylog** [comment]
I have not been able to reproduce this with both 1.7.1 and the current dev image with the document given above.

I'm still confused by the dpkg information.  You're not updating packages within the container right?

**Comment by upuldi** [comment]
What fixed the issue was the masking of the sensitive information and republishing the PDFs. As you said updated PDF (I shared) is processing without any issues. However, the original file I have is not. Anyway, I am closing this issue as this seems like a PDF issue. Maybe it is missing some bits. :)

@stumpylog  Thank you for your prompt responses and support.
